//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4uTest
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int ID { get; set; }


        [Required(ErrorMessage = "Debe ingresar un nombre"),
         MinLength(2, ErrorMessage ="{0} debe tener al menos {1} caracteres"),
         MaxLength(50, ErrorMessage = "No sobrepase el límite de 50 caracteres")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Debe ingresar un correo"), 
         MinLength(2, ErrorMessage = "{0} debe tener al menos {1} caracteres"),
         MaxLength(50, ErrorMessage = "No sobrepase el límite de 50 caracteres"),
         EmailAddress(ErrorMessage = "Debe ingresar un correo válido")]
        public string Correo { get; set; }
    }
}
